services:

  postgres:
    image: postgres:16-alpine
    container_name: abac-postgres
    environment:
      POSTGRES_DB: abacdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev2026
    ports:
      - "5432:5432"
    volumes:
      - abac-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d abacdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  opa:
    image: openpolicyagent/opa:latest
    container_name: abac-opa
    command: run --server --log-level=info --addr=0.0.0.0:8181
    ports:
      - "8181:8181"
    volumes:
      - ./opa/policies:/policies

volumes:
  abac-postgres-data: