spring.application.name=abac-service

spring.datasource.url=jdbc:postgresql://127.0.0.1:5434/abacdb
spring.datasource.username=postgres
spring.datasource.password=dev2026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration,org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration

spring.h2.console.enabled=false

opa.url=http://localhost:8181
opa.policy-path=/v1/data/abac/allow

spring.devtools.restart.enabled=false

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

server.port=8002